name: Deploy to Nife
on: [push]
jobs:
    deploy:
      name: Deploy proxy
      runs-on: ubuntu-latest
      steps:
        # This step checks out a copy of your repository.
        - uses: actions/checkout@v2
        # This step runs nifectl deploy.
        - uses: nifetency/nife-actions@2.4
          env:
            NIFE_ACCESS_TOKEN: ${{ secrets.NIFE_ACCESS_TOKEN }}
          with:
            args: "deploy --remote-only"
